routes:
  - path: "/api"
    targets:
      - "http://localhost:5001"
      - "http://localhost:5003"
    rewrite: "/"

  - path: "/auth"
    target: "http://localhost:5002"
    auth:
      username: "admin"
      password: "1234"
    rewrite: "/"
