name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu klonla
        uses: actions/checkout@v3

      - name: Go kurulumu
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Go test
        run: go test -v ./...

      - name: Docker kurulumu
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-api ./api-backend
